export type FirmPlan = 'solo' | 'pro' | 'team' | 'firm'
export type FirmStatus = 'active' | 'suspended' | 'deleted'
export type FirmRole = 'owner' | 'partner' | 'manager' | 'preparer' | 'coordinator'
export type MemberStatus = 'active' | 'suspended'
export type InvitationStatus = 'pending' | 'expired' | 'canceled'

export type ClientEntityType =
  | 'llc'
  | 's_corp'
  | 'partnership'
  | 'c_corp'
  | 'sole_prop'
  | 'trust'
  | 'individual'
  | 'other'

export type ClientLegalEntity =
  | 'individual'
  | 'sole_proprietorship'
  | 'single_member_llc'
  | 'multi_member_llc'
  | 'partnership'
  | 'corporation'
  | 'trust'
  | 'estate'
  | 'nonprofit'
  | 'foreign_entity'
  | 'other'

// Lifecycle v2: `blocked` and `completed` are non-breaking additions.
// See docs/Design/obligation-lifecycle-design-brief.md.
export type ObligationStatus =
  | 'pending'
  | 'in_progress'
  | 'done'
  | 'extended'
  | 'paid'
  | 'waiting_on_client'
  | 'review'
  | 'not_applicable'
  | 'blocked'
  | 'completed'

export type ObligationReadiness = 'ready' | 'waiting' | 'needs_review'

export type ObligationExtensionDecision = 'not_considered' | 'applied' | 'rejected'

export type ExposureStatus = 'ready' | 'needs_input' | 'unsupported'

export type ClientTaxClassification =
  | 'individual'
  | 'disregarded_entity'
  | 'partnership'
  | 's_corp'
  | 'c_corp'
  | 'trust'
  | 'estate'
  | 'nonprofit'
  | 'foreign_reporting_company'
  | 'unknown'

export type TaxYearType = 'calendar' | 'fiscal'
export type TaxPeriodKind = 'calendar' | 'fiscal' | 'short' | '52_53_week' | 'unknown'
export type TaxPeriodSource =
  | 'client_default'
  | 'prior_obligation'
  | 'migration'
  | 'manual_cpa_confirmed'
  | 'unknown'

export type ObligationType =
  | 'filing'
  | 'payment'
  | 'deposit'
  | 'information'
  | 'client_action'
  | 'internal_review'
export type ObligationRecurrence =
  | 'once'
  | 'annual'
  | 'quarterly'
  | 'monthly'
  | 'semiweekly'
  | 'event_triggered'
export type ObligationRiskLevel = 'low' | 'med' | 'high'
export type ObligationPrepStage =
  | 'not_started'
  | 'waiting_on_client'
  | 'waiting_on_third_party'
  | 'bookkeeping_cleanup'
  | 'ready_for_prep'
  | 'in_prep'
  | 'prepared'
export type ObligationReviewStage =
  | 'not_required'
  | 'ready_for_review'
  | 'in_review'
  | 'notes_open'
  | 'approved'
  | 'overridden'
export type ObligationExtensionState =
  | 'not_applicable'
  | 'not_started'
  | 'estimate_needed'
  | 'client_approval_needed'
  | 'ready_to_file'
  | 'filed'
  | 'accepted'
  | 'rejected'
export type ObligationPaymentState =
  | 'not_applicable'
  | 'estimate_needed'
  | 'client_approval_needed'
  | 'scheduled'
  | 'confirmed'
export type ObligationEfileState =
  | 'not_applicable'
  | 'authorization_requested'
  | 'authorization_signed'
  | 'ready_to_submit'
  | 'submitted'
  | 'accepted'
  | 'rejected'
  | 'corrected_resubmitted'
  | 'paper_filed'
  | 'final_package_delivered'

export type MigrationSource =
  | 'paste'
  | 'csv'
  | 'xlsx'
  | 'preset_taxdome'
  | 'preset_drake'
  | 'preset_karbon'
  | 'preset_quickbooks'
  | 'preset_file_in_time'
  | 'preset_cch_axcess'
  | 'preset_cch_prosystem_fx'
  | 'preset_lacerte'
  | 'preset_proseries'
  | 'preset_ultratax_cs'
  | 'preset_proconnect_tax'

export type MigrationBatchStatus =
  | 'draft'
  | 'mapping'
  | 'reviewing'
  | 'applied'
  | 'reverted'
  | 'failed'

export type AiOutputKind =
  | 'brief'
  | 'tip'
  | 'summary'
  | 'ask_answer'
  | 'pulse_extract'
  | 'rule_concrete_draft'
  | 'migration_map'
  | 'migration_normalize'
  | 'readiness_checklist'

export type AuditActionCategory =
  | 'client'
  | 'obligation'
  | 'migration'
  | 'rules'
  | 'auth'
  | 'team'
  | 'pulse'
  | 'export'
  | 'ai'
  | 'system'

export type ObligationQueueSort = 'smart_priority' | 'due_asc' | 'due_desc' | 'updated_desc'
export type ObligationQueueOwnerFilter = 'unassigned'
export type ObligationQueueDueFilter = 'overdue'
export type ObligationQueueReadiness = ObligationReadiness
export type DashboardSeverity = 'critical' | 'high' | 'medium' | 'neutral'
export type DashboardDueBucket = 'overdue' | 'today' | 'next_7_days' | 'next_30_days' | 'long_term'
export type DashboardEvidenceFilter = 'needs' | 'linked'
export type DashboardBriefScope = 'firm' | 'me'
export type DashboardBriefStatus = 'pending' | 'ready' | 'failed' | 'stale'
export type WorkloadOwnerKind = 'assignee' | 'unassigned'
