import { useMemo } from 'react'
import { useLingui } from '@lingui/react/macro'

import type { AuditChangeLabels } from './audit-change-view'
import type { AuditActionLabels, AuditEntityTypeLabels } from './audit-log-model'

export function useAuditActionLabels(): AuditActionLabels {
  const { t } = useLingui()

  return useMemo(
    () => ({
      aiGuardFailed: t`AI guard failed`,
      aiRefusal: t`AI refused request`,
      askQueryRun: t`Ask query run`,
      authDenied: t`Access denied`,
      authLoginFailed: t`Sign-in failed`,
      authLoginSuccess: t`Sign-in succeeded`,
      authMfaDisabled: t`Two-factor disabled`,
      authMfaEnabled: t`Two-factor enabled`,
      authMfaSetupStarted: t`Two-factor setup started`,
      authSessionRevoked: t`Session revoked`,
      clientAssigneeUpdated: t`Client assignee changed`,
      clientBatchCreated: t`Client batch created`,
      clientCreated: t`Client created`,
      clientDeleted: t`Client deleted`,
      clientFilingProfilesReplaced: t`Filing profile updated`,
      clientJurisdictionUpdated: t`Filing jurisdictions updated`,
      clientRiskProfileUpdated: t`Risk profile updated`,
      clientSourceDetailsUpdated: t`Client details updated`,
      clientTaxYearProfileUpdated: t`Tax year settings updated`,
      exportAuditPackageDownloaded: t`Audit export downloaded`,
      exportAuditPackageFailed: t`Audit export failed`,
      exportAuditPackageReady: t`Audit export ready`,
      exportAuditPackageRequested: t`Audit export requested`,
      firmCreated: t`Practice created`,
      firmDeleted: t`Practice deleted`,
      firmSwitched: t`Practice switched`,
      firmUpdated: t`Practice updated`,
      memberAccepted: t`Member accepted`,
      memberInvitationCanceled: t`Invitation canceled`,
      memberInvitationResent: t`Invitation resent`,
      memberInvited: t`Member invited`,
      memberReactivated: t`Member reactivated`,
      memberRemoved: t`Member removed`,
      memberRoleUpdated: t`Member role changed`,
      memberSuspended: t`Member suspended`,
      migrationBatchCreated: t`Import batch created`,
      migrationImported: t`Import completed`,
      migrationMapperConfirmed: t`Import mapping confirmed`,
      migrationMatrixApplied: t`Tax type suggestions applied`,
      migrationNormalizerConfirmed: t`Import normalization confirmed`,
      migrationRawUploaded: t`Import file uploaded`,
      migrationReverted: t`Import reverted`,
      migrationSingleUndo: t`Imported client undone`,
      obligationAnnualRolloverCreated: t`Annual rollover created`,
      readinessChecklistItemAiOverridden: t`Overrode AI suggestion`,
      readinessChecklistItemCreated: t`Materials item added`,
      readinessChecklistItemDeleted: t`Materials item removed`,
      readinessChecklistItemUpdated: t`Materials item updated`,
      obligationBatchCreated: t`Deadlines created`,
      obligationDueDateUpdated: t`Internal deadline changed`,
      obligationExtensionDecided: t`Extension plan saved`,
      obligationInputRequested: t`Input requested`,
      obligationReadinessUpdated: t`Materials state changed`,
      obligationStatusUpdated: t`Deadline status changed`,
      obligationTaxYearProfileUpdated: t`Deadline tax year changed`,
      onboardingAgentDryRunPreviewed: t`Onboarding dry run previewed`,
      onboardingAgentFallbackTriggered: t`Onboarding alternate path used`,
      onboardingAgentHandoffChosen: t`Onboarding handoff chosen`,
      onboardingAgentHandoffOffered: t`Onboarding handoff offered`,
      onboardingAgentImportCommitted: t`Onboarding import committed`,
      onboardingAgentIntakeSubmitted: t`Onboarding intake submitted`,
      onboardingAgentMatrixPreloaded: t`Onboarding matrix preloaded`,
      onboardingAgentNormalizeConfirmed: t`Onboarding normalization confirmed`,
      onboardingAgentPreviewCardClicked: t`Onboarding preview opened`,
      onboardingAgentStateAdvanced: t`Onboarding state advanced`,
      onboardingAgentTurnOpened: t`Onboarding turn opened`,
      opportunityDismissed: t`Opportunity dismissed`,
      opportunityRestored: t`Opportunity restored`,
      opportunitySnoozed: t`Opportunity snoozed`,
      penaltyOverride: t`Penalty inputs changed`,
      pulseApply: t`Alert applied`,
      pulseApprove: t`Alert approved`,
      pulseDismiss: t`Alert dismissed`,
      pulseExtract: t`Alert update extracted`,
      pulseIngest: t`Alert source ingested`,
      pulseQuarantine: t`Alert quarantined`,
      pulseReactivate: t`Alert reactivated`,
      pulseReject: t`Alert rejected`,
      pulseRevert: t`Alert reverted`,
      pulseReviewRequested: t`Alert review requested`,
      pulseSnooze: t`Alert snoozed`,
      pulseSourceRevoked: t`Alert source revoked`,
      roleCheck: t`Permission checked`,
      ruleReportIssue: t`Rule issue reported`,
      ruleUpdated: t`Rule updated`,
      ruleVerified: t`Rule accepted`,
      rulesCandidateCreated: t`Pending rule queued`,
      rulesAccepted: t`Rule accepted`,
      rulesBulkAccepted: t`Rules accepted in bulk`,
      rulesOnboardingActivated: t`Onboarding rules activated`,
      rulesRejected: t`Rule rejected`,
      rulesCreated: t`Custom rule created`,
      rulesUpdated: t`Practice rule updated`,
      rulesArchived: t`Practice rule archived`,
      rulesPublished: t`Rules accepted`,
      rulesReviewRejected: t`Rule rejected`,
      rulesReviewRequired: t`Rule review required`,
      rulesSourceChanged: t`Rule source changed`,
      obligationQueueExported: t`Deadlines exported`,
      obligationQueueSavedViewCreated: t`Saved view created`,
      obligationQueueSavedViewDeleted: t`Saved view deleted`,
      obligationQueueSavedViewUpdated: t`Saved view updated`,
    }),
    [t],
  )
}

export function useAuditEntityTypeLabels(): AuditEntityTypeLabels {
  const { t } = useLingui()

  return useMemo(
    () => ({
      auth: t`Authentication`,
      auditEvidencePackage: t`Audit export package`,
      client: t`Client`,
      clientBatch: t`Client import batch`,
      firm: t`Practice`,
      member: t`Team member`,
      memberInvitation: t`Member invitation`,
      migrationBatch: t`Import batch`,
      obligationBatch: t`Deadline batch`,
      obligationInstance: t`Deadline`,
      pulseApplication: t`Alert application`,
      pulseAlert: t`Alert`,
      rule: t`Rule`,
      ruleSource: t`Rule source`,
      obligationQueueExport: t`Deadlines export`,
      obligationQueueSavedView: t`Saved deadline view`,
      opportunity: t`Opportunity`,
    }),
    [t],
  )
}

export function useAuditChangeLabels({
  actionLabels,
  readinessLabels,
  statusLabels,
}: {
  actionLabels: AuditActionLabels
  readinessLabels: Record<string, string>
  statusLabels: Record<string, string>
}): AuditChangeLabels {
  const { t } = useLingui()

  return useMemo(
    () => ({
      actionLabels,
      statusLabels,
      readinessLabels,
      fields: {
        alertStatus: t`Alert status`,
        assigneeName: t`Assignee`,
        cells: t`Rule cells`,
        clientCount: t`Clients`,
        clientsAffected: t`Clients affected`,
        contentType: t`File type`,
        count: t`Rows`,
        createdCount: t`Created deadlines`,
        currentDueDate: t`Internal deadline`,
        disabledCells: t`Disabled cells`,
        email: t`Email`,
        enabledCells: t`Enabled cells`,
        equityOwnerCount: t`Owner count`,
        errorCount: t`Rows needing attention`,
        estimatedTaxLiabilityCents: t`Estimated tax liability`,
        fileCount: t`Files`,
        fileName: t`File`,
        format: t`Format`,
        isPinned: t`Pinned`,
        kind: t`File kind`,
        matchedCount: t`Matched clients`,
        name: t`Name`,
        needsReviewCount: t`Needs review`,
        obligationCount: t`Deadlines`,
        plan: t`Plan`,
        presetUsed: t`Preset`,
        pulseStatus: t`Alert status`,
        readiness: t`Materials state`,
        recipientName: t`Recipient`,
        recipientRole: t`Recipient role`,
        role: t`Role`,
        rowCount: t`Rows`,
        scope: t`Scope`,
        seatLimit: t`Seat limit`,
        sizeBytes: t`File size`,
        skippedCount: t`Skipped rows`,
        snoozedUntil: t`Snoozed until`,
        source: t`Source`,
        sourceFilingYear: t`Source filing year`,
        status: t`Status`,
        targetFilingYear: t`Target filing year`,
        timezone: t`Timezone`,
      },
      values: {
        detailsUpdated: t`Details updated`,
        multipleValues: t`Multiple values`,
        no: t`No`,
        none: t`None`,
        notRecorded: t`Not recorded`,
        notSet: t`Not set`,
        unchanged: t`Unchanged`,
        yes: t`Yes`,
      },
      enumValues: {
        active: t`Active`,
        all_ignore: t`All ignored`,
        applied: t`Applied`,
        canceled: t`Canceled`,
        coordinator: t`Coordinator`,
        csv: t`CSV`,
        dismissed: t`Dismissed`,
        failed: t`Failed`,
        Firm: t`Firm`,
        manager: t`Manager`,
        manual: t`Manual`,
        mapping: t`Mapping`,
        matched: t`Matched`,
        owner: t`Owner`,
        partner: t`Partner`,
        pending: statusLabels.pending ?? t`Pending`,
        pending_review: t`Needs review`,
        preparer: t`Preparer`,
        preset: t`Preset`,
        quarantined: t`Quarantined`,
        rejected: t`Rejected`,
        reviewing: t`Reviewing`,
        revoked: t`Revoked`,
        snoozed: t`Snoozed`,
        suspended: t`Suspended`,
        tsv: t`TSV`,
        xlsx: t`XLSX`,
      },
      headlines: {
        actionRecorded: (action) => t`${action} recorded`,
        assigneeChanged: (assignee, count) =>
          count === null
            ? t`Client assignee changed to ${assignee}`
            : t`Client assignee changed to ${assignee} for ${count} clients`,
        batchCreated: (action, count) =>
          count === null ? t`${action} recorded` : t`${action}: ${count} rows`,
        deadlineDueDateChanged: (previous, next) =>
          t`Internal deadline changed from ${previous} to ${next}`,
        deadlineReadinessChanged: (previous, next) =>
          t`Materials state changed from ${previous} to ${next}`,
        deadlineStatusChanged: (previous, next) =>
          t`Deadline status changed from ${previous} to ${next}`,
        fieldChanged: (field, previous, next) => t`${field} changed from ${previous} to ${next}`,
        firmUpdated: t`Practice profile changed`,
        importCompleted: (clientCount, obligationCount, skippedCount) =>
          t`Import completed: ${clientCount ?? 0} clients, ${obligationCount ?? 0} deadlines, ${skippedCount ?? 0} skipped rows`,
        memberRoleChanged: (previous, next) => t`Member role changed from ${previous} to ${next}`,
        multipleFieldsChanged: (action, count) => t`${action}: ${count} fields changed`,
        penaltyInputsChanged: t`Penalty inputs changed`,
        pulseDueDateChanged: (previous, next) =>
          t`Alert changed due date from ${previous} to ${next}`,
        savedViewUpdated: (name) => (name ? t`Saved view updated: ${name}` : t`Saved view updated`),
      },
      notes: {
        additionalChanges: (count) => t`${count} additional fields changed`,
        countUpdated: (count, noun) => t`${count} ${noun} updated`,
        noDetailedSnapshot: t`Event recorded without a detailed change snapshot.`,
        noFieldChange: t`No user-facing field change was recorded.`,
      },
      nouns: {
        clients: t`clients`,
        deadlines: t`deadlines`,
        events: t`events`,
        files: t`files`,
        fields: t`fields`,
        rows: t`rows`,
      },
    }),
    [actionLabels, readinessLabels, statusLabels, t],
  )
}
