/**
 * IconsRoute — `/icons`. A reference gallery of every lucide icon used across
 * DueDateHQ (one entry per unique glyph, normalized to the `*Icon` export name).
 * Click an icon to copy its import name. Internal design utility — plain English,
 * not localized, same as `/preview`.
 *
 * SNAPSHOT generated 2026-06-18 (post icon-audit merge). To refresh after icons
 * change, re-run:
 *   perl -0777 -ne 'while (/import\s*\{([^}]*)\}\s*from\s*["\x27]lucide-react["\x27]/gs){print "$1\n"}' \
 *     $(grep -rl "from '"'"'lucide-react'"'"'" apps/app/src packages/ui/src | grep -v routes/icons.tsx) \
 *     | tr ',' '\n' | sed -E 's#//.*##; s/\s//g' | grep -E '^[A-Za-z]' \
 *     | grep -v '^typeLucideIcon$' | sed -E 's/Icon$//' | sort -u | sed 's/$/Icon/'
 * then rebuild the ICONS array below.
 */
import { useMemo, useState } from 'react'
import {
  ActivityIcon,
  AlarmClockIcon,
  AppWindowIcon,
  ArchiveIcon,
  ArrowDownIcon,
  ArrowDownUpIcon,
  ArrowLeftIcon,
  ArrowRightIcon,
  ArrowRightLeftIcon,
  ArrowUpIcon,
  ArrowUpFromLineIcon,
  ArrowUpRightIcon,
  AtSignIcon,
  BanIcon,
  BellIcon,
  BellRingIcon,
  BookOpenIcon,
  BookmarkIcon,
  BriefcaseIcon,
  Building2Icon,
  CalculatorIcon,
  CalendarIcon,
  CalendarClockIcon,
  CalendarDaysIcon,
  CalendarPlusIcon,
  CalendarRangeIcon,
  CalendarSearchIcon,
  CheckIcon,
  CheckCheckIcon,
  ChevronDownIcon,
  ChevronLeftIcon,
  ChevronRightIcon,
  ChevronUpIcon,
  ChevronsUpDownIcon,
  CircleIcon,
  CircleAlertIcon,
  CircleCheckIcon,
  CircleCheckBigIcon,
  CircleDollarSignIcon,
  CircleHelpIcon,
  CircleOffIcon,
  CirclePlayIcon,
  CircleSlash2Icon,
  ClipboardCheckIcon,
  ClipboardListIcon,
  ClockIcon,
  Clock3Icon,
  CoffeeIcon,
  Columns3Icon,
  ConstructionIcon,
  CopyIcon,
  CornerDownLeftIcon,
  CreditCardIcon,
  CrosshairIcon,
  CrownIcon,
  DollarSignIcon,
  DownloadIcon,
  Edit3Icon,
  EllipsisIcon,
  EllipsisVerticalIcon,
  ExternalLinkIcon,
  EyeIcon,
  FileArchiveIcon,
  FileCheckIcon,
  FileCheck2Icon,
  FileEditIcon,
  FilePenIcon,
  FilePenLineIcon,
  FilePlus2Icon,
  FileSearchIcon,
  FileSpreadsheetIcon,
  FileTextIcon,
  FilterIcon,
  FlameIcon,
  GaugeIcon,
  GavelIcon,
  GitPullRequestArrowIcon,
  GlobeIcon,
  HistoryIcon,
  HomeIcon,
  HourglassIcon,
  InboxIcon,
  InfoIcon,
  KeyRoundIcon,
  LandmarkIcon,
  LaptopIcon,
  LayersIcon,
  LayoutDashboardIcon,
  LibraryIcon,
  LightbulbIcon,
  LinkIcon,
  Link2Icon,
  ListIcon,
  ListChecksIcon,
  ListFilterIcon,
  LoaderIcon,
  Loader2Icon,
  LoaderCircleIcon,
  LockIcon,
  LockKeyholeIcon,
  LogOutIcon,
  MailIcon,
  MailCheckIcon,
  MapIcon,
  MapPinIcon,
  Maximize2Icon,
  MegaphoneIcon,
  MessageSquareIcon,
  MessageSquareTextIcon,
  MinusIcon,
  MinusCircleIcon,
  MonitorIcon,
  MoonIcon,
  NewspaperIcon,
  OctagonAlertIcon,
  OctagonXIcon,
  PaperclipIcon,
  PauseCircleIcon,
  PenLineIcon,
  PencilIcon,
  PencilLineIcon,
  PhoneIcon,
  PlayIcon,
  PlusIcon,
  PlusCircleIcon,
  QrCodeIcon,
  RadioIcon,
  ReceiptTextIcon,
  RefreshCwIcon,
  RepeatIcon,
  RotateCcwIcon,
  RotateCwIcon,
  RssIcon,
  SatelliteDishIcon,
  ScaleIcon,
  ScrollTextIcon,
  SearchIcon,
  SearchXIcon,
  SendIcon,
  ServerIcon,
  ServerCogIcon,
  SettingsIcon,
  ShieldIcon,
  ShieldAlertIcon,
  ShieldCheckIcon,
  ShuffleIcon,
  SkipForwardIcon,
  SlidersHorizontalIcon,
  SmartphoneIcon,
  SparklesIcon,
  SquareIcon,
  SquareChartGanttIcon,
  SquareCheckIcon,
  StarIcon,
  SunIcon,
  TagIcon,
  TimerIcon,
  Trash2Icon,
  TrendingDownIcon,
  TrendingUpIcon,
  TriangleAlertIcon,
  Undo2Icon,
  UnlinkIcon,
  UploadIcon,
  UploadCloudIcon,
  UserCheckIcon,
  UserPlusIcon,
  UserRoundIcon,
  UserRoundCogIcon,
  UsersIcon,
  XIcon,
  type LucideIcon,
} from 'lucide-react'
import { Input } from '@duedatehq/ui/components/ui/input'
import { toast } from 'sonner'

const ICONS: ReadonlyArray<{ name: string; Icon: LucideIcon }> = [
  { name: 'ActivityIcon', Icon: ActivityIcon },
  { name: 'AlarmClockIcon', Icon: AlarmClockIcon },
  { name: 'AppWindowIcon', Icon: AppWindowIcon },
  { name: 'ArchiveIcon', Icon: ArchiveIcon },
  { name: 'ArrowDownIcon', Icon: ArrowDownIcon },
  { name: 'ArrowDownUpIcon', Icon: ArrowDownUpIcon },
  { name: 'ArrowLeftIcon', Icon: ArrowLeftIcon },
  { name: 'ArrowRightIcon', Icon: ArrowRightIcon },
  { name: 'ArrowRightLeftIcon', Icon: ArrowRightLeftIcon },
  { name: 'ArrowUpIcon', Icon: ArrowUpIcon },
  { name: 'ArrowUpFromLineIcon', Icon: ArrowUpFromLineIcon },
  { name: 'ArrowUpRightIcon', Icon: ArrowUpRightIcon },
  { name: 'AtSignIcon', Icon: AtSignIcon },
  { name: 'BanIcon', Icon: BanIcon },
  { name: 'BellIcon', Icon: BellIcon },
  { name: 'BellRingIcon', Icon: BellRingIcon },
  { name: 'BookOpenIcon', Icon: BookOpenIcon },
  { name: 'BookmarkIcon', Icon: BookmarkIcon },
  { name: 'BriefcaseIcon', Icon: BriefcaseIcon },
  { name: 'Building2Icon', Icon: Building2Icon },
  { name: 'CalculatorIcon', Icon: CalculatorIcon },
  { name: 'CalendarIcon', Icon: CalendarIcon },
  { name: 'CalendarClockIcon', Icon: CalendarClockIcon },
  { name: 'CalendarDaysIcon', Icon: CalendarDaysIcon },
  { name: 'CalendarPlusIcon', Icon: CalendarPlusIcon },
  { name: 'CalendarRangeIcon', Icon: CalendarRangeIcon },
  { name: 'CalendarSearchIcon', Icon: CalendarSearchIcon },
  { name: 'CheckIcon', Icon: CheckIcon },
  { name: 'CheckCheckIcon', Icon: CheckCheckIcon },
  { name: 'ChevronDownIcon', Icon: ChevronDownIcon },
  { name: 'ChevronLeftIcon', Icon: ChevronLeftIcon },
  { name: 'ChevronRightIcon', Icon: ChevronRightIcon },
  { name: 'ChevronUpIcon', Icon: ChevronUpIcon },
  { name: 'ChevronsUpDownIcon', Icon: ChevronsUpDownIcon },
  { name: 'CircleIcon', Icon: CircleIcon },
  { name: 'CircleAlertIcon', Icon: CircleAlertIcon },
  { name: 'CircleCheckIcon', Icon: CircleCheckIcon },
  { name: 'CircleCheckBigIcon', Icon: CircleCheckBigIcon },
  { name: 'CircleDollarSignIcon', Icon: CircleDollarSignIcon },
  { name: 'CircleHelpIcon', Icon: CircleHelpIcon },
  { name: 'CircleOffIcon', Icon: CircleOffIcon },
  { name: 'CirclePlayIcon', Icon: CirclePlayIcon },
  { name: 'CircleSlash2Icon', Icon: CircleSlash2Icon },
  { name: 'ClipboardCheckIcon', Icon: ClipboardCheckIcon },
  { name: 'ClipboardListIcon', Icon: ClipboardListIcon },
  { name: 'ClockIcon', Icon: ClockIcon },
  { name: 'Clock3Icon', Icon: Clock3Icon },
  { name: 'CoffeeIcon', Icon: CoffeeIcon },
  { name: 'Columns3Icon', Icon: Columns3Icon },
  { name: 'ConstructionIcon', Icon: ConstructionIcon },
  { name: 'CopyIcon', Icon: CopyIcon },
  { name: 'CornerDownLeftIcon', Icon: CornerDownLeftIcon },
  { name: 'CreditCardIcon', Icon: CreditCardIcon },
  { name: 'CrosshairIcon', Icon: CrosshairIcon },
  { name: 'CrownIcon', Icon: CrownIcon },
  { name: 'DollarSignIcon', Icon: DollarSignIcon },
  { name: 'DownloadIcon', Icon: DownloadIcon },
  { name: 'Edit3Icon', Icon: Edit3Icon },
  { name: 'EllipsisIcon', Icon: EllipsisIcon },
  { name: 'EllipsisVerticalIcon', Icon: EllipsisVerticalIcon },
  { name: 'ExternalLinkIcon', Icon: ExternalLinkIcon },
  { name: 'EyeIcon', Icon: EyeIcon },
  { name: 'FileArchiveIcon', Icon: FileArchiveIcon },
  { name: 'FileCheckIcon', Icon: FileCheckIcon },
  { name: 'FileCheck2Icon', Icon: FileCheck2Icon },
  { name: 'FileEditIcon', Icon: FileEditIcon },
  { name: 'FilePenIcon', Icon: FilePenIcon },
  { name: 'FilePenLineIcon', Icon: FilePenLineIcon },
  { name: 'FilePlus2Icon', Icon: FilePlus2Icon },
  { name: 'FileSearchIcon', Icon: FileSearchIcon },
  { name: 'FileSpreadsheetIcon', Icon: FileSpreadsheetIcon },
  { name: 'FileTextIcon', Icon: FileTextIcon },
  { name: 'FilterIcon', Icon: FilterIcon },
  { name: 'FlameIcon', Icon: FlameIcon },
  { name: 'GaugeIcon', Icon: GaugeIcon },
  { name: 'GavelIcon', Icon: GavelIcon },
  { name: 'GitPullRequestArrowIcon', Icon: GitPullRequestArrowIcon },
  { name: 'GlobeIcon', Icon: GlobeIcon },
  { name: 'HistoryIcon', Icon: HistoryIcon },
  { name: 'HomeIcon', Icon: HomeIcon },
  { name: 'HourglassIcon', Icon: HourglassIcon },
  { name: 'InboxIcon', Icon: InboxIcon },
  { name: 'InfoIcon', Icon: InfoIcon },
  { name: 'KeyRoundIcon', Icon: KeyRoundIcon },
  { name: 'LandmarkIcon', Icon: LandmarkIcon },
  { name: 'LaptopIcon', Icon: LaptopIcon },
  { name: 'LayersIcon', Icon: LayersIcon },
  { name: 'LayoutDashboardIcon', Icon: LayoutDashboardIcon },
  { name: 'LibraryIcon', Icon: LibraryIcon },
  { name: 'LightbulbIcon', Icon: LightbulbIcon },
  { name: 'LinkIcon', Icon: LinkIcon },
  { name: 'Link2Icon', Icon: Link2Icon },
  { name: 'ListIcon', Icon: ListIcon },
  { name: 'ListChecksIcon', Icon: ListChecksIcon },
  { name: 'ListFilterIcon', Icon: ListFilterIcon },
  { name: 'LoaderIcon', Icon: LoaderIcon },
  { name: 'Loader2Icon', Icon: Loader2Icon },
  { name: 'LoaderCircleIcon', Icon: LoaderCircleIcon },
  { name: 'LockIcon', Icon: LockIcon },
  { name: 'LockKeyholeIcon', Icon: LockKeyholeIcon },
  { name: 'LogOutIcon', Icon: LogOutIcon },
  { name: 'MailIcon', Icon: MailIcon },
  { name: 'MailCheckIcon', Icon: MailCheckIcon },
  { name: 'MapIcon', Icon: MapIcon },
  { name: 'MapPinIcon', Icon: MapPinIcon },
  { name: 'Maximize2Icon', Icon: Maximize2Icon },
  { name: 'MegaphoneIcon', Icon: MegaphoneIcon },
  { name: 'MessageSquareIcon', Icon: MessageSquareIcon },
  { name: 'MessageSquareTextIcon', Icon: MessageSquareTextIcon },
  { name: 'MinusIcon', Icon: MinusIcon },
  { name: 'MinusCircleIcon', Icon: MinusCircleIcon },
  { name: 'MonitorIcon', Icon: MonitorIcon },
  { name: 'MoonIcon', Icon: MoonIcon },
  { name: 'NewspaperIcon', Icon: NewspaperIcon },
  { name: 'OctagonAlertIcon', Icon: OctagonAlertIcon },
  { name: 'OctagonXIcon', Icon: OctagonXIcon },
  { name: 'PaperclipIcon', Icon: PaperclipIcon },
  { name: 'PauseCircleIcon', Icon: PauseCircleIcon },
  { name: 'PenLineIcon', Icon: PenLineIcon },
  { name: 'PencilIcon', Icon: PencilIcon },
  { name: 'PencilLineIcon', Icon: PencilLineIcon },
  { name: 'PhoneIcon', Icon: PhoneIcon },
  { name: 'PlayIcon', Icon: PlayIcon },
  { name: 'PlusIcon', Icon: PlusIcon },
  { name: 'PlusCircleIcon', Icon: PlusCircleIcon },
  { name: 'QrCodeIcon', Icon: QrCodeIcon },
  { name: 'RadioIcon', Icon: RadioIcon },
  { name: 'ReceiptTextIcon', Icon: ReceiptTextIcon },
  { name: 'RefreshCwIcon', Icon: RefreshCwIcon },
  { name: 'RepeatIcon', Icon: RepeatIcon },
  { name: 'RotateCcwIcon', Icon: RotateCcwIcon },
  { name: 'RotateCwIcon', Icon: RotateCwIcon },
  { name: 'RssIcon', Icon: RssIcon },
  { name: 'SatelliteDishIcon', Icon: SatelliteDishIcon },
  { name: 'ScaleIcon', Icon: ScaleIcon },
  { name: 'ScrollTextIcon', Icon: ScrollTextIcon },
  { name: 'SearchIcon', Icon: SearchIcon },
  { name: 'SearchXIcon', Icon: SearchXIcon },
  { name: 'SendIcon', Icon: SendIcon },
  { name: 'ServerIcon', Icon: ServerIcon },
  { name: 'ServerCogIcon', Icon: ServerCogIcon },
  { name: 'SettingsIcon', Icon: SettingsIcon },
  { name: 'ShieldIcon', Icon: ShieldIcon },
  { name: 'ShieldAlertIcon', Icon: ShieldAlertIcon },
  { name: 'ShieldCheckIcon', Icon: ShieldCheckIcon },
  { name: 'ShuffleIcon', Icon: ShuffleIcon },
  { name: 'SkipForwardIcon', Icon: SkipForwardIcon },
  { name: 'SlidersHorizontalIcon', Icon: SlidersHorizontalIcon },
  { name: 'SmartphoneIcon', Icon: SmartphoneIcon },
  { name: 'SparklesIcon', Icon: SparklesIcon },
  { name: 'SquareIcon', Icon: SquareIcon },
  { name: 'SquareChartGanttIcon', Icon: SquareChartGanttIcon },
  { name: 'SquareCheckIcon', Icon: SquareCheckIcon },
  { name: 'StarIcon', Icon: StarIcon },
  { name: 'SunIcon', Icon: SunIcon },
  { name: 'TagIcon', Icon: TagIcon },
  { name: 'TimerIcon', Icon: TimerIcon },
  { name: 'Trash2Icon', Icon: Trash2Icon },
  { name: 'TrendingDownIcon', Icon: TrendingDownIcon },
  { name: 'TrendingUpIcon', Icon: TrendingUpIcon },
  { name: 'TriangleAlertIcon', Icon: TriangleAlertIcon },
  { name: 'Undo2Icon', Icon: Undo2Icon },
  { name: 'UnlinkIcon', Icon: UnlinkIcon },
  { name: 'UploadIcon', Icon: UploadIcon },
  { name: 'UploadCloudIcon', Icon: UploadCloudIcon },
  { name: 'UserCheckIcon', Icon: UserCheckIcon },
  { name: 'UserPlusIcon', Icon: UserPlusIcon },
  { name: 'UserRoundIcon', Icon: UserRoundIcon },
  { name: 'UserRoundCogIcon', Icon: UserRoundCogIcon },
  { name: 'UsersIcon', Icon: UsersIcon },
  { name: 'XIcon', Icon: XIcon },
]

export function IconsRoute() {
  const [query, setQuery] = useState('')
  const filtered = useMemo(() => {
    const needle = query.trim().toLowerCase()
    if (!needle) return ICONS
    return ICONS.filter((entry) => entry.name.toLowerCase().includes(needle))
  }, [query])

  function copyName(name: string) {
    void navigator.clipboard?.writeText(name).then(
      () => toast.success(`Copied ${name}`),
      () => toast.error("Couldn't copy"),
    )
  }

  return (
    <div className="mx-auto w-full max-w-[1080px] px-6 py-10">
      <header className="mb-5 flex flex-col gap-1">
        <h1 className="text-2xl font-semibold tracking-tight text-text-primary">Icons</h1>
        <p className="text-sm text-text-tertiary">
          {ICONS.length} lucide icons used across DueDateHQ. Click any icon to copy its import name.
          Snapshot 2026-06-18.
        </p>
      </header>

      <div className="sticky top-0 z-10 -mx-6 mb-5 flex items-center gap-3 border-b border-divider-subtle bg-background-default/90 px-6 py-3 backdrop-blur">
        <Input
          value={query}
          onChange={(event) => setQuery(event.target.value)}
          placeholder="Filter icons…"
          className="max-w-xs"
          aria-label="Filter icons"
        />
        <span className="shrink-0 text-xs tabular-nums text-text-tertiary">
          {filtered.length} shown
        </span>
      </div>

      {filtered.length === 0 ? (
        <p className="py-16 text-center text-sm text-text-tertiary">No matching icons.</p>
      ) : (
        <div className="grid grid-cols-[repeat(auto-fill,minmax(110px,1fr))] gap-2">
          {filtered.map(({ name, Icon }) => (
            <button
              key={name}
              type="button"
              onClick={() => copyName(name)}
              title={`Copy ${name}`}
              className="group flex flex-col items-center gap-2 rounded-lg border border-divider-subtle bg-background-default px-2 py-3 text-center transition-colors hover:border-divider-regular hover:bg-background-section focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-state-accent-active-alt"
            >
              <Icon
                className="size-5 text-text-secondary transition-colors group-hover:text-text-primary"
                aria-hidden
              />
              <span className="w-full truncate text-[11px] font-medium text-text-tertiary">
                {name}
              </span>
            </button>
          ))}
        </div>
      )}
    </div>
  )
}
