import { useState, type SyntheticEvent } from 'react'
import { useNavigate, useSearchParams } from 'react-router'
import { useMutation, useQueryClient } from '@tanstack/react-query'
import { Trans, useLingui } from '@lingui/react/macro'
import { ArrowRightIcon, Loader2Icon } from 'lucide-react'
import { toast } from 'sonner'

import { Button } from '@duedatehq/ui/components/ui/button'
import { AuthCard, CenteredAuthScreen } from '@/features/auth/auth-chrome'
import { OtpInput } from '@/features/auth/otp-input'
import { signOut } from '@/lib/auth'
import { orpc } from '@/lib/rpc'
import { rpcErrorMessage } from '@/lib/rpc-error'

// /two-factor uses the full-bleed CenteredAuthScreen so it matches the /login
// language (brand bar + trust line + footer). It's wired as a standalone route
// (no EntryShell parent) in router.tsx. Copy is truthful for TOTP (the code is
// generated by the app, not "sent"); the recovery-code branch stays deferred —
// the support mailto is the live escape.
export function TwoFactorRoute() {
  const { t } = useLingui()
  const navigate = useNavigate()
  const queryClient = useQueryClient()
  const [search] = useSearchParams()
  const [code, setCode] = useState('')

  const verifyMutation = useMutation(
    orpc.security.verifyTwoFactor.mutationOptions({
      onSuccess: async () => {
        toast.success(t`Two-factor verification complete`)
        await queryClient.invalidateQueries()
        await navigate(search.get('redirectTo') || '/', { replace: true })
      },
      onError: (err) => {
        toast.error(t`Couldn't verify the code`, {
          description: rpcErrorMessage(err) ?? err.message,
        })
      },
    }),
  )

  function submit(value: string) {
    const trimmed = value.trim()
    if (trimmed.length < 6 || verifyMutation.isPending) return
    verifyMutation.mutate({ code: trimmed })
  }

  function handleSubmit(event: SyntheticEvent<HTMLFormElement>) {
    event.preventDefault()
    submit(code)
  }

  // Auto-submit once six digits are entered — standard pattern (Stripe,
  // GitHub). Guards on pending so a slow network can't double-submit.
  function handleCodeChange(next: string) {
    setCode(next)
    if (next.trim().length === 6) submit(next)
  }

  return (
    <CenteredAuthScreen>
      <AuthCard>
        <form onSubmit={handleSubmit} className="flex flex-col gap-7">
          {/* Heading */}
          <div className="flex flex-col gap-2">
            <h1 className="text-[28px] sm:text-[30px] font-semibold leading-[1.15] tracking-[-0.6px] text-text-primary">
              <Trans>Check your phone</Trans>
            </h1>
            <p className="text-sm font-medium leading-normal text-text-tertiary">
              <Trans>
                Open your authenticator app and enter the 6-digit code it shows for DueDateHQ.
              </Trans>
            </p>
          </div>

          {/* Code field */}
          <div className="flex flex-col gap-3.5">
            <div className="flex items-center gap-2">
              <label
                htmlFor="two-factor-code"
                className="text-xs font-semibold text-text-secondary"
              >
                <Trans>Verification code</Trans>
              </label>
              <span className="flex-1" />
              <span className="text-[11px] font-medium italic text-text-tertiary">
                <Trans>refreshes every 30s</Trans>
              </span>
            </div>
            <OtpInput
              id="two-factor-code"
              value={code}
              onChange={handleCodeChange}
              disabled={verifyMutation.isPending}
              invalid={verifyMutation.isError}
              autoFocus
              aria-describedby="two-factor-code-helper"
            />
            <div className="flex flex-col items-start gap-1.5">
              <span
                id="two-factor-code-helper"
                className="whitespace-nowrap text-[11px] font-medium text-text-tertiary"
              >
                <Trans>Google Authenticator, 1Password, Authy, or similar.</Trans>
              </span>
              <a
                href="mailto:support@duedatehq.com?subject=Two-factor%20recovery"
                className="text-xs font-medium text-text-accent transition-colors hover:text-text-accent-secondary"
              >
                <Trans>Lost your authenticator?</Trans>
              </a>
            </div>
          </div>

          {/* Primary CTA */}
          <Button
            type="submit"
            className="h-12 w-full justify-center gap-2 rounded-lg font-semibold"
            disabled={verifyMutation.isPending || code.trim().length < 6}
            aria-busy={verifyMutation.isPending || undefined}
          >
            {verifyMutation.isPending ? (
              <Loader2Icon className="size-4 animate-spin" aria-hidden />
            ) : (
              <>
                <Trans>Verify &amp; continue</Trans>
                <ArrowRightIcon className="size-4" aria-hidden />
              </>
            )}
          </Button>

          {/* Sign out escape */}
          <p className="flex items-center justify-center gap-1.5 text-center">
            <span className="text-xs font-medium text-text-tertiary">
              <Trans>Not your device?</Trans>
            </span>
            <Button
              variant="ghost"
              size="xs"
              onClick={() => {
                void signOut().finally(() => navigate('/login', { replace: true }))
              }}
              className="text-text-secondary hover:text-text-primary"
            >
              <Trans>Sign out</Trans>
            </Button>
          </p>
        </form>
      </AuthCard>
    </CenteredAuthScreen>
  )
}
