/* eslint-disable typescript-eslint/no-unsafe-type-assertion --
 * drizzle-orm doesn't export a public `enumValues` field on AnySQLiteColumn,
 * but it's set at runtime by the `text({ enum: [...] })` builder. The cast
 * is the documented escape hatch for this exact case.
 */
import { describe, expect, it } from 'vitest'
import { getTableName } from 'drizzle-orm'
import { getTableConfig, type AnySQLiteColumn } from 'drizzle-orm/sqlite-core'
import { firmProfile, type FirmProfile, type NewFirmProfile } from './schema/firm'

/**
 * Schema-shape tests using drizzle's runtime introspection (`getTableConfig`).
 *
 * Why not @cloudflare/vitest-pool-workers + miniflare D1?
 *   The plan called for D1 enum/FK validation, but packages/db has no
 *   vitest-pool-workers config today and adding it just for one schema test
 *   is significant infra (miniflare wiring + migration replay + worker pool).
 *   The migration SQL output (packages/db/migrations/0001_tidy_shiva.sql) was
 *   generated by drizzle-kit and visually verified to contain the correct
 *   FOREIGN KEY ... ON DELETE cascade / restrict clauses; this test locks
 *   down the TS-level schema definition that produced that SQL.
 *
 * Recorded as a plan deviation in
 * docs/dev-log/2026-04-24-first-login-practice-onboarding.md.
 */

function findColumn(name: string): AnySQLiteColumn {
  const cfg = getTableConfig(firmProfile)
  const col = cfg.columns.find((c) => c.name === name)
  if (!col) throw new Error(`firm_profile column ${name} not found in TS schema`)
  return col
}

describe('firm_profile schema', () => {
  it('uses the expected table name', () => {
    expect(getTableConfig(firmProfile).name).toBe('firm_profile')
  })

  it('exposes every business-tenant column with the right SQL types', () => {
    const cfg = getTableConfig(firmProfile)
    const byName = Object.fromEntries(cfg.columns.map((c) => [c.name, c]))

    expect(Object.keys(byName).toSorted()).toEqual(
      [
        'id',
        'name',
        'plan',
        'seat_limit',
        'timezone',
        'internal_deadline_offset_days',
        'monitoring_start_date',
        'owner_user_id',
        'status',
        'billing_customer_id',
        'billing_subscription_id',
        'coordinator_can_see_dollars',
        'smart_priority_profile_json',
        'created_at',
        'updated_at',
        'deleted_at',
      ].toSorted(),
    )

    // Spot-check SQL types (drizzle reports these as the underlying SQLite types).
    expect(byName.id?.getSQLType()).toBe('text')
    expect(byName.seat_limit?.getSQLType()).toBe('integer')
    expect(byName.internal_deadline_offset_days?.getSQLType()).toBe('integer')
    expect(byName.monitoring_start_date?.getSQLType()).toBe('text')
    expect(byName.coordinator_can_see_dollars?.getSQLType()).toBe('integer')
    expect(byName.smart_priority_profile_json?.getSQLType()).toBe('text')
    expect(byName.created_at?.getSQLType()).toBe('integer')
    expect(byName.deleted_at?.getSQLType()).toBe('integer')
  })

  it('declares id as PRIMARY KEY and notNull', () => {
    const id = findColumn('id')
    expect(id.primary).toBe(true)
    expect(id.notNull).toBe(true)
  })

  it('makes name / owner_user_id required and deleted_at optional', () => {
    expect(findColumn('name').notNull).toBe(true)
    expect(findColumn('owner_user_id').notNull).toBe(true)
    expect(findColumn('deleted_at').notNull).toBe(false)
  })

  it('defaults plan to free / status to active / seatLimit to 1 / timezone to NY', () => {
    expect(findColumn('plan').default).toBe('free')
    expect(findColumn('status').default).toBe('active')
    expect(findColumn('seat_limit').default).toBe(1)
    expect(findColumn('timezone').default).toBe('America/New_York')
    expect(findColumn('internal_deadline_offset_days').default).toBe(14)
    expect(findColumn('monitoring_start_date').notNull).toBe(true)
    expect(findColumn('coordinator_can_see_dollars').default).toBe(false)
  })

  it('declares the plan and status enums (drizzle-side enum values)', () => {
    const planCol = findColumn('plan') as AnySQLiteColumn & { enumValues?: readonly string[] }
    const statusCol = findColumn('status') as AnySQLiteColumn & { enumValues?: readonly string[] }
    expect(planCol.enumValues).toEqual(['free', 'solo', 'pro', 'team', 'firm'])
    expect(statusCol.enumValues).toEqual(['active', 'suspended', 'deleted'])
  })

  it('wires id → organization.id (cascade) and owner_user_id → user.id (restrict)', () => {
    const cfg = getTableConfig(firmProfile)

    const idFk = cfg.foreignKeys.find((fk) => fk.reference().columns.some((c) => c.name === 'id'))
    expect(idFk).toBeDefined()
    const idRef = idFk!.reference()
    expect(getTableName(idRef.foreignTable)).toBe('organization')
    expect(idRef.foreignColumns.map((c) => c.name)).toEqual(['id'])
    expect(idFk!.onDelete).toBe('cascade')

    const ownerFk = cfg.foreignKeys.find((fk) =>
      fk.reference().columns.some((c) => c.name === 'owner_user_id'),
    )
    expect(ownerFk).toBeDefined()
    const ownerRef = ownerFk!.reference()
    expect(getTableName(ownerRef.foreignTable)).toBe('user')
    expect(ownerRef.foreignColumns.map((c) => c.name)).toEqual(['id'])
    expect(ownerFk!.onDelete).toBe('restrict')
  })

  it('enforces TS-level shape on inferred select / insert types', () => {
    // Compile-time assertion: if these expressions stop compiling, the
    // schema's TS surface has shifted in a way every consumer should review.
    const sample: FirmProfile = {
      id: 'firm_1',
      name: 'Bright CPA Practice',
      plan: 'solo',
      seatLimit: 1,
      timezone: 'America/New_York',
      internalDeadlineOffsetDays: 14,
      monitoringStartDate: '2026-05-29',
      ownerUserId: 'user_1',
      status: 'active',
      billingCustomerId: null,
      billingSubscriptionId: null,
      coordinatorCanSeeDollars: false,
      smartPriorityProfileJson: null,
      createdAt: new Date(),
      updatedAt: new Date(),
      deletedAt: null,
    }
    const insert: NewFirmProfile = {
      id: 'firm_2',
      name: 'Other Practice',
      ownerUserId: 'user_2',
    }
    expect(sample.id).toBe('firm_1')
    expect(insert.name).toBe('Other Practice')
  })
})
