// Custom ORPCError code table shared across packages.
// Codes enumerated in Phase 0 as procedures land; keep stable and never reuse values.

export const ErrorCodes = {
  TENANT_MISSING: 'TENANT_MISSING',
  TENANT_MISMATCH: 'TENANT_MISMATCH',
  TENANT_SUSPENDED: 'TENANT_SUSPENDED',
  RATE_LIMITED: 'RATE_LIMITED',
  VALIDATION: 'VALIDATION',
  AI_BUDGET_EXCEEDED: 'AI_BUDGET_EXCEEDED',
  GUARD_REJECTED: 'GUARD_REJECTED',
  FIRM_NOT_FOUND: 'FIRM_NOT_FOUND',
  FIRM_FORBIDDEN: 'FIRM_FORBIDDEN',
  FIRM_LIMIT_EXCEEDED: 'FIRM_LIMIT_EXCEEDED',
  FIRM_DELETED: 'FIRM_DELETED',
  MEMBER_FORBIDDEN: 'MEMBER_FORBIDDEN',
  MEMBER_NOT_FOUND: 'MEMBER_NOT_FOUND',
  MEMBER_SEAT_LIMIT: 'MEMBER_SEAT_LIMIT',
  MEMBER_DUPLICATE: 'MEMBER_DUPLICATE',
  INVITATION_NOT_FOUND: 'INVITATION_NOT_FOUND',
  INVITATION_DUPLICATE: 'INVITATION_DUPLICATE',
  MEMBER_SELF_ACTION_FORBIDDEN: 'MEMBER_SELF_ACTION_FORBIDDEN',
  MEMBER_OWNER_ACTION_FORBIDDEN: 'MEMBER_OWNER_ACTION_FORBIDDEN',
  PULSE_NOT_FOUND: 'PULSE_NOT_FOUND',
  PULSE_APPLY_CONFLICT: 'PULSE_APPLY_CONFLICT',
  PULSE_REVERT_EXPIRED: 'PULSE_REVERT_EXPIRED',
  PULSE_NO_ELIGIBLE_OBLIGATIONS: 'PULSE_NO_ELIGIBLE_OBLIGATIONS',
  PULSE_NEEDS_DETAILS: 'PULSE_NEEDS_DETAILS',
  PULSE_REVIEW_UNAVAILABLE: 'PULSE_REVIEW_UNAVAILABLE',
  PULSE_REVIEW_ONLY: 'PULSE_REVIEW_ONLY',
  WORKLOAD_PLAN_REQUIRED: 'WORKLOAD_PLAN_REQUIRED',
} as const

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes]
