import { oc } from '@orpc/contract'
import * as z from 'zod'
import { AuditEventPublicSchema } from './audit'
import { EvidencePublicSchema } from './evidence'
import { ObligationInstancePublicSchema } from './obligation-instance'
import { SmartPriorityBreakdownSchema } from './priority'
import {
  ClientReadinessRequestPublicSchema,
  ReadinessDocumentChecklistItemPublicSchema,
} from './readiness'
import { ExtensionPolicySchema, RuleEvidenceSchema } from './rules'
import { ObligationReadinessSchema, ObligationStatusSchema, StateCodeSchema } from './shared/enums'
import { EntityIdSchema, TenantIdSchema } from './shared/ids'

/**
 * Obligations is the firm-wide obligation queue. Read-only here; mutations
 * live in `obligationsContract` (createBatch, updateDueDate, updateStatus)
 * to keep one canonical write path per entity.
 *
 * Cursor pagination follows D1 100-bound-param budget — we encode the active
 * sort value plus stable row identity so the next page query does not need a
 * wide parameter payload.
 */

export const ObligationQueueSortSchema = z.enum([
  'smart_priority',
  'due_asc',
  'due_desc',
  'updated_desc',
])
export type ObligationQueueSort = z.infer<typeof ObligationQueueSortSchema>
export const ObligationQueueDensitySchema = z.enum(['comfortable', 'compact'])
export type ObligationQueueDensity = z.infer<typeof ObligationQueueDensitySchema>
export const ObligationQueueOwnerFilterSchema = z.enum(['unassigned'])
export type ObligationQueueOwnerFilter = z.infer<typeof ObligationQueueOwnerFilterSchema>
export const ObligationQueueDueFilterSchema = z.enum(['overdue'])
export type ObligationQueueDueFilter = z.infer<typeof ObligationQueueDueFilterSchema>
export const ObligationQueueReadinessSchema = ObligationReadinessSchema
export type ObligationQueueReadiness = z.infer<typeof ObligationQueueReadinessSchema>
export const OBLIGATION_QUEUE_SEARCH_MAX_LENGTH = 64
export const OBLIGATION_QUEUE_FILTER_MAX_SELECTIONS = 16
export const OBLIGATION_QUEUE_FILTER_VALUE_MAX_LENGTH = 120

const ObligationQueueFilterValueSchema = z
  .string()
  .trim()
  .min(1)
  .max(OBLIGATION_QUEUE_FILTER_VALUE_MAX_LENGTH)

export const ObligationQueueListInputSchema = z.object({
  status: z.array(ObligationStatusSchema).max(8).optional(),
  search: z.string().max(OBLIGATION_QUEUE_SEARCH_MAX_LENGTH).optional(),
  obligationIds: z.array(EntityIdSchema).max(OBLIGATION_QUEUE_FILTER_MAX_SELECTIONS).optional(),
  clientIds: z.array(EntityIdSchema).max(OBLIGATION_QUEUE_FILTER_MAX_SELECTIONS).optional(),
  // Filter to obligations generated by specific rules. Lets the Rule
  // library deep-link into the queue so CPAs can audit what a given
  // rule actually produced ("which clients does this trigger for?").
  // NOT EntityIdSchema: obligation.rule_id is a free-text catalog id
  // (e.g. "ny.it204.return.2025") until the Phase-1 rule_id FK lands —
  // a uuid gate here silently rejected every real rule deep-link.
  ruleIds: z
    .array(ObligationQueueFilterValueSchema)
    .max(OBLIGATION_QUEUE_FILTER_MAX_SELECTIONS)
    .optional(),
  states: z.array(StateCodeSchema).max(OBLIGATION_QUEUE_FILTER_MAX_SELECTIONS).optional(),
  counties: z
    .array(ObligationQueueFilterValueSchema)
    .max(OBLIGATION_QUEUE_FILTER_MAX_SELECTIONS)
    .optional(),
  taxTypes: z
    .array(ObligationQueueFilterValueSchema)
    .max(OBLIGATION_QUEUE_FILTER_MAX_SELECTIONS)
    .optional(),
  assigneeName: z.string().trim().min(1).max(120).optional(),
  assigneeNames: z
    .array(ObligationQueueFilterValueSchema)
    .max(OBLIGATION_QUEUE_FILTER_MAX_SELECTIONS)
    .optional(),
  owner: ObligationQueueOwnerFilterSchema.optional(),
  due: ObligationQueueDueFilterSchema.optional(),
  dueWithinDays: z.number().int().min(1).max(30).optional(),
  readiness: z.array(ObligationQueueReadinessSchema).max(3).optional(),
  minDaysUntilDue: z.number().int().min(-3650).max(3650).optional(),
  maxDaysUntilDue: z.number().int().min(-3650).max(3650).optional(),
  needsEvidence: z.boolean().optional(),
  // "Awaiting signature" lens — returns only rows where the return is
  // marked filed but the client hasn't signed Form 8879 yet (status='done'
  // AND efileState='authorization_requested'). The combined predicate is
  // deliberate: efileState alone is unreliable because new filing
  // obligations are seeded with 'authorization_requested' at creation.
  awaitingSignature: z.boolean().optional(),
  // Projected/confirmed lens. `false` returns only projected (annual-rollover /
  // auto-projection) deadlines awaiting CPA confirmation; `true` only confirmed.
  confirmed: z.boolean().optional(),
  // Pinned lens. `true` returns only deadlines the CPA has starred — powers the
  // dashboard "Pinned" section. Omitted = no pin filter.
  pinned: z.boolean().optional(),
  // Snoozed lens. Omitted = default behavior (snoozed rows stay hidden until
  // their return instant). 'only' returns just the currently-snoozed rows —
  // powers the /deadlines "N snoozed" notice so a snoozed deadline can still
  // be FOUND before it returns. 'include' disables the snooze filter entirely.
  snoozed: z.enum(['include', 'only']).optional(),
  asOfDate: z.iso.date().optional(),
  sort: ObligationQueueSortSchema.default('smart_priority').optional(),
  cursor: z.string().nullable().optional(),
  limit: z.number().int().min(1).max(100).default(50).optional(),
})
export type ObligationQueueListInput = z.infer<typeof ObligationQueueListInputSchema>

export const ObligationQueueRowSchema = ObligationInstancePublicSchema.omit({
  // 2026-06-08 (Yuqi /deadlines design parity): estimatedExposureCents is
  // un-omitted to power the production design's EXPOSURE column (per-row $
  // headline + accrued-penalty subtext). The 2026-05-21 "remove per-row $"
  // call is intentionally reversed here per the design-supersedes decision.
  // exposureStatus / exposureCalculatedAt stay omitted — the queue only needs
  // the headline number, not the calc provenance.
  exposureStatus: true,
  exposureCalculatedAt: true,
}).extend({
  // Projected lifecycle gate (annual rollover / auto-projection). Surfaced so the
  // queue can badge projected rows and filter the Projected lens.
  confirmed: z.boolean(),
  clientName: z.string().min(1),
  clientState: StateCodeSchema.nullable(),
  clientCounty: ObligationQueueFilterValueSchema.nullable(),
  // Client entity type (llc / s_corp / sole_prop / trust / …). Surfaced so the
  // queue CLIENT cell can render the "Sole Prop · California" identity subtitle
  // (Pencil /deadlines production recreation). Mirrors clients.entity_type.
  clientEntityType: z.enum([
    'llc',
    's_corp',
    'partnership',
    'c_corp',
    'sole_prop',
    'trust',
    'individual',
    'other',
  ]),
  assigneeName: z.string().min(1).nullable(),
  taxYearProfileEditable: z.boolean(),
  readiness: ObligationQueueReadinessSchema,
  daysUntilDue: z.number().int(),
  evidenceCount: z.number().int().min(0),
  smartPriority: SmartPriorityBreakdownSchema,
})
export type ObligationQueueRow = z.infer<typeof ObligationQueueRowSchema>

export const ObligationQueueListOutputSchema = z.object({
  rows: z.array(ObligationQueueRowSchema),
  nextCursor: z.string().nullable(),
})
export type ObligationQueueListOutput = z.infer<typeof ObligationQueueListOutputSchema>

export const ObligationQueueFacetOptionSchema = z.object({
  value: ObligationQueueFilterValueSchema,
  label: z.string().trim().min(1).max(160),
  count: z.number().int().min(0),
})
export type ObligationQueueFacetOption = z.infer<typeof ObligationQueueFacetOptionSchema>

export const ObligationQueueClientFacetOptionSchema = ObligationQueueFacetOptionSchema.extend({
  value: EntityIdSchema,
  state: StateCodeSchema.nullable(),
  county: ObligationQueueFilterValueSchema.nullable(),
})
export type ObligationQueueClientFacetOption = z.infer<
  typeof ObligationQueueClientFacetOptionSchema
>

export const ObligationQueueCountyFacetOptionSchema = ObligationQueueFacetOptionSchema.extend({
  state: StateCodeSchema.nullable(),
})
export type ObligationQueueCountyFacetOption = z.infer<
  typeof ObligationQueueCountyFacetOptionSchema
>

export const ObligationQueueFacetsOutputSchema = z.object({
  clients: z.array(ObligationQueueClientFacetOptionSchema),
  states: z.array(ObligationQueueFacetOptionSchema),
  counties: z.array(ObligationQueueCountyFacetOptionSchema),
  taxTypes: z.array(ObligationQueueFacetOptionSchema),
  assigneeNames: z.array(ObligationQueueFacetOptionSchema),
  statuses: z.array(ObligationQueueFacetOptionSchema),
})
export type ObligationQueueFacetsOutput = z.infer<typeof ObligationQueueFacetsOutputSchema>

export const ObligationQueueSavedViewQuerySchema = z.record(z.string(), z.unknown())
export type ObligationQueueSavedViewQuery = z.infer<typeof ObligationQueueSavedViewQuerySchema>

export const ObligationQueueColumnVisibilitySchema = z.record(z.string(), z.boolean())
export type ObligationQueueColumnVisibility = z.infer<typeof ObligationQueueColumnVisibilitySchema>

export const ObligationQueueSavedViewSchema = z.object({
  id: EntityIdSchema,
  firmId: TenantIdSchema,
  createdByUserId: z.string().min(1),
  name: z.string().trim().min(1).max(80),
  query: ObligationQueueSavedViewQuerySchema,
  columnVisibility: ObligationQueueColumnVisibilitySchema,
  density: ObligationQueueDensitySchema,
  isPinned: z.boolean(),
  createdAt: z.iso.datetime(),
  updatedAt: z.iso.datetime(),
})
export type ObligationQueueSavedView = z.infer<typeof ObligationQueueSavedViewSchema>

export const ObligationQueueCreateSavedViewInputSchema = z.object({
  name: z.string().trim().min(1).max(80),
  query: ObligationQueueSavedViewQuerySchema,
  columnVisibility: ObligationQueueColumnVisibilitySchema.default({}).optional(),
  density: ObligationQueueDensitySchema.default('comfortable').optional(),
  isPinned: z.boolean().default(false).optional(),
})
export type ObligationQueueCreateSavedViewInput = z.infer<
  typeof ObligationQueueCreateSavedViewInputSchema
>

export const ObligationQueueUpdateSavedViewInputSchema = z.object({
  id: EntityIdSchema,
  name: z.string().trim().min(1).max(80).optional(),
  query: ObligationQueueSavedViewQuerySchema.optional(),
  columnVisibility: ObligationQueueColumnVisibilitySchema.optional(),
  density: ObligationQueueDensitySchema.optional(),
  isPinned: z.boolean().optional(),
})
export type ObligationQueueUpdateSavedViewInput = z.infer<
  typeof ObligationQueueUpdateSavedViewInputSchema
>

export const ObligationQueueDeleteSavedViewInputSchema = z.object({ id: EntityIdSchema })
export type ObligationQueueDeleteSavedViewInput = z.infer<
  typeof ObligationQueueDeleteSavedViewInputSchema
>

export const ObligationQueueExportQuerySchema = ObligationQueueListInputSchema.omit({
  cursor: true,
  limit: true,
})
export type ObligationQueueExportQuery = z.infer<typeof ObligationQueueExportQuerySchema>
export const ObligationQueueExportScopeSchema = z.enum(['selected', 'filtered', 'all_active'])
export type ObligationQueueExportScope = z.infer<typeof ObligationQueueExportScopeSchema>
export const ObligationQueueExportFormatSchema = z.enum(['pdf_zip', 'csv', 'ics'])
export type ObligationQueueExportFormat = z.infer<typeof ObligationQueueExportFormatSchema>

export const ObligationQueueExportSelectedInputSchema = z
  .object({
    ids: z.array(EntityIdSchema).max(1000).optional(),
    scope: ObligationQueueExportScopeSchema.default('selected'),
    query: ObligationQueueExportQuerySchema.optional(),
    format: ObligationQueueExportFormatSchema,
  })
  .superRefine((input, ctx) => {
    if (input.scope === 'selected' && (!input.ids || input.ids.length === 0)) {
      ctx.addIssue({
        code: 'custom',
        path: ['ids'],
        message: 'Select at least one obligation to export.',
      })
    }
    if (input.scope === 'filtered' && !input.query) {
      ctx.addIssue({
        code: 'custom',
        path: ['query'],
        message: 'Filtered exports require a query.',
      })
    }
  })
export type ObligationQueueExportSelectedInput = z.infer<
  typeof ObligationQueueExportSelectedInputSchema
>

export const ObligationQueueExportSelectedOutputSchema = z.object({
  fileName: z.string().min(1),
  contentType: z.string().min(1),
  contentBase64: z.string().min(1),
  auditId: EntityIdSchema,
})
export type ObligationQueueExportSelectedOutput = z.infer<
  typeof ObligationQueueExportSelectedOutputSchema
>

export const ObligationQueueDetailTabSchema = z.enum([
  // 2026-05-25 (Yuqi Deadlines #30): added `summary` as the new
  // default-first tab. Hosts the milestone chevron + active-stage
  // card (previously pinned in the sticky block) so the milestone
  // story has a labeled tab home. The PrimaryDeadlineStrip (3
  // anchor dates) stays sticky above the tabs — those numbers are
  // always-visible context, not summary content.
  'summary',
  'readiness',
  'extension',
  'risk',
  'evidence',
  'audit',
])
export type ObligationQueueDetailTab = z.infer<typeof ObligationQueueDetailTabSchema>

export const ObligationQueueMatchedRuleSchema = z.object({
  id: z.string().min(1),
  title: z.string().min(1),
  defaultTip: z.string().min(1),
  taxYearProfileEditable: z.boolean(),
  extensionPolicy: ExtensionPolicySchema,
  evidence: z.array(RuleEvidenceSchema),
})
export type ObligationQueueMatchedRule = z.infer<typeof ObligationQueueMatchedRuleSchema>

export const ObligationQueueDetailInputSchema = z.object({
  obligationId: EntityIdSchema,
  asOfDate: z.iso.date().optional(),
})
export type ObligationQueueDetailInput = z.infer<typeof ObligationQueueDetailInputSchema>

export const ObligationQueueDetailSchema = z.object({
  row: ObligationQueueRowSchema,
  matchedRule: ObligationQueueMatchedRuleSchema.nullable(),
  evidence: z.array(EvidencePublicSchema),
  auditEvents: z.array(AuditEventPublicSchema),
  readinessChecklist: z.array(ReadinessDocumentChecklistItemPublicSchema),
  readinessRequests: z.array(ClientReadinessRequestPublicSchema),
})
export type ObligationQueueDetail = z.infer<typeof ObligationQueueDetailSchema>

/**
 * Pin / unpin a single deadline. `isPinned` true stars it (surfaces in the
 * dashboard Pinned section); false un-stars. Returns the new flag + the audit
 * id so the UI can optimistically reconcile.
 */
export const ObligationQueueSetPinnedInputSchema = z.object({
  obligationId: EntityIdSchema,
  isPinned: z.boolean(),
})
export type ObligationQueueSetPinnedInput = z.infer<typeof ObligationQueueSetPinnedInputSchema>

export const ObligationQueueSetPinnedOutputSchema = z.object({
  obligationId: EntityIdSchema,
  isPinned: z.boolean(),
  auditId: EntityIdSchema,
})
export type ObligationQueueSetPinnedOutput = z.infer<typeof ObligationQueueSetPinnedOutputSchema>

export const obligationQueueContract = oc.router({
  list: oc.input(ObligationQueueListInputSchema).output(ObligationQueueListOutputSchema),
  getDetail: oc.input(ObligationQueueDetailInputSchema).output(ObligationQueueDetailSchema),
  setPinned: oc
    .input(ObligationQueueSetPinnedInputSchema)
    .output(ObligationQueueSetPinnedOutputSchema),
  facets: oc.input(z.undefined()).output(ObligationQueueFacetsOutputSchema),
  listSavedViews: oc.input(z.undefined()).output(z.array(ObligationQueueSavedViewSchema)),
  createSavedView: oc
    .input(ObligationQueueCreateSavedViewInputSchema)
    .output(ObligationQueueSavedViewSchema),
  updateSavedView: oc
    .input(ObligationQueueUpdateSavedViewInputSchema)
    .output(ObligationQueueSavedViewSchema),
  deleteSavedView: oc
    .input(ObligationQueueDeleteSavedViewInputSchema)
    .output(z.object({ id: EntityIdSchema })),
  exportSelected: oc
    .input(ObligationQueueExportSelectedInputSchema)
    .output(ObligationQueueExportSelectedOutputSchema),
})
export type ObligationQueueContract = typeof obligationQueueContract
