import { Trans, useLingui } from '@lingui/react/macro'
import { SparklesIcon } from 'lucide-react'

import { cn } from '@duedatehq/ui/lib/utils'
import { Tooltip, TooltipContent, TooltipTrigger } from '@duedatehq/ui/components/ui/tooltip'

import { formatDateTimeWithTimezone } from '@/lib/utils'

/**
 * AiProvenanceBadge — canonical "AI generated this value" marker.
 *
 * Renders the SparklesIcon icon next to (or instead of) a piece of text the
 * AI authored. The badge is intentionally small and quiet — provenance
 * disclosure, not visual noise. Pairs with a tooltip that exposes WHEN
 * the AI produced it and HOW the user can override it.
 *
 * Used for the readiness checklist SparklesIcon marker. The marker DROPS once
 * the user value-edits the row (server-side: origin flips to 'manual',
 * userEditedAt stamps) — this badge simply renders the new state.
 *
 * ## When to use
 *  - Per-value AI authorship (a row in a list, a fact in a card).
 *  - For aggregate / feature-level AI signalling, use the `SparklesIcon`
 *    icon directly (e.g. concept-help popovers, command palette).
 *
 * ## Tone notes
 *  - Quiet text color (text-text-tertiary) — provenance is reference
 *    information, not a call-to-action. The user already sees the
 *    value; the badge whispers "AI was the author."
 *  - On hover, the tooltip explains "Edit this item to confirm" so
 *    users learn the F-022 override convention without a help panel.
 */
export function AiProvenanceBadge({
  generatedAt,
  firmTimezone,
  className,
  variant = 'inline',
}: {
  generatedAt: string | null
  // Optional — when missing, the tooltip falls back to a locale string.
  // The audit drawer (which always has firmTimezone) is the high-fidelity
  // consumer; the readiness checklist surface defers to browser locale.
  firmTimezone?: string
  className?: string
  // 'inline' → small dot-icon for inside a row's title.
  // 'chip'   → bordered pill for standalone placements (audit drawer).
  variant?: 'inline' | 'chip'
}) {
  const { t } = useLingui()
  const generatedLabel = generatedAt
    ? firmTimezone
      ? formatDateTimeWithTimezone(generatedAt, firmTimezone)
      : new Date(generatedAt).toLocaleString()
    : null

  if (variant === 'chip') {
    return (
      <Tooltip>
        <TooltipTrigger
          className={cn(
            'inline-flex h-5 cursor-help items-center gap-1 rounded-sm border border-divider-regular bg-background-subtle px-1.5 text-caption font-medium text-text-secondary',
            className,
          )}
          aria-label={t`Generated by AI`}
        >
          <SparklesIcon className="size-3" aria-hidden />
          <Trans>AI</Trans>
        </TooltipTrigger>
        <TooltipContent>
          <AiProvenanceTooltipBody generatedLabel={generatedLabel} />
        </TooltipContent>
      </Tooltip>
    )
  }

  return (
    <Tooltip>
      <TooltipTrigger
        className={cn('inline-flex cursor-help items-center text-text-tertiary', className)}
        aria-label={t`Generated by AI`}
      >
        <SparklesIcon className="size-3.5" aria-hidden />
      </TooltipTrigger>
      <TooltipContent>
        <AiProvenanceTooltipBody generatedLabel={generatedLabel} />
      </TooltipContent>
    </Tooltip>
  )
}

function AiProvenanceTooltipBody({ generatedLabel }: { generatedLabel: string | null }) {
  return (
    <div className="flex max-w-[240px] flex-col gap-1 text-left">
      <span className="text-caption-xs font-medium uppercase tracking-eyebrow-tight">
        <Trans>Generated by AI</Trans>
      </span>
      {generatedLabel ? (
        <span className="text-caption text-components-tooltip-text">{generatedLabel}</span>
      ) : null}
      <span className="text-caption-xs leading-snug opacity-80">
        <Trans>Edit this item to confirm the value. The AI marker will drop.</Trans>
      </span>
    </div>
  )
}
